### ISSUE TITLE
Paper filename counter resets in every session

### ISSUE THREAD

**Issue by clange** [ceurws/ceur-make#25]
Solution: use different XPath expression

**Comment by csarven** [comment]
Just to document here and to keep alternative options in mind: paper counter (i.e., the order) may not be of importance to the reader. Consider displaying a total paper count of the proceedings.

**Comment by clange** [comment]
@csarven, I was not speaking of displaying the counter (e.g. using `<ol>`). I was speaking of auto-generating URLs like `paper-01.pdf` if there is no `/toc//paper/@id`.

**Comment by csarven** [comment]
:+1:  I misread :)
